# Travis build settings for go-commonmark
language: go
go:
 - 1.3
 - 1.4
before_install:
 - sudo add-apt-repository ppa:kalakris/cmake
 - sudo apt-get update -qq
 - sudo apt-get install gcc
 - sudo apt-get install build-essential
 - sudo apt-get install cmake
 - sudo apt-get install re2c
 - sudo apt-get install pandoc
 - git clone https://github.com/jgm/CommonMark ~/cm
 - cd ~/cm
 - make 
 - sudo make install
 - LD_LIBRARY_PATH=/usr/local/lib
 - export LD_LIBRARY_PATH
 - cd $HOME/gopath/src/github.com/rhinoman/go-commonmark
script:
 - go test -v ./...
